// +build !ignore_autogenerated

// Code generated by openapi-gen. DO NOT EDIT.

// This file was autogenerated by openapi-gen. Do not edit it manually!

package v1alpha1

import (
	spec "github.com/go-openapi/spec"
	common "k8s.io/kube-openapi/pkg/common"
)

func GetOpenAPIDefinitions(ref common.ReferenceCallback) map[string]common.OpenAPIDefinition {
	return map[string]common.OpenAPIDefinition{
		"github.com/example-inc/app-operator/pkg/apis/kafka/v1alpha1.BrokerOperator":          schema_pkg_apis_kafka_v1alpha1_BrokerOperator(ref),
		"github.com/example-inc/app-operator/pkg/apis/kafka/v1alpha1.BrokerOperatorSpec":      schema_pkg_apis_kafka_v1alpha1_BrokerOperatorSpec(ref),
		"github.com/example-inc/app-operator/pkg/apis/kafka/v1alpha1.BrokerOperatorStatus":    schema_pkg_apis_kafka_v1alpha1_BrokerOperatorStatus(ref),
		"github.com/example-inc/app-operator/pkg/apis/kafka/v1alpha1.ZooKeeperOperator":       schema_pkg_apis_kafka_v1alpha1_ZooKeeperOperator(ref),
		"github.com/example-inc/app-operator/pkg/apis/kafka/v1alpha1.ZooKeeperOperatorSpec":   schema_pkg_apis_kafka_v1alpha1_ZooKeeperOperatorSpec(ref),
		"github.com/example-inc/app-operator/pkg/apis/kafka/v1alpha1.ZooKeeperOperatorStatus": schema_pkg_apis_kafka_v1alpha1_ZooKeeperOperatorStatus(ref),
	}
}

func schema_pkg_apis_kafka_v1alpha1_BrokerOperator(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "BrokerOperator is the Schema for the brokeroperators API",
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/example-inc/app-operator/pkg/apis/kafka/v1alpha1.BrokerOperatorSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/example-inc/app-operator/pkg/apis/kafka/v1alpha1.BrokerOperatorStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"github.com/example-inc/app-operator/pkg/apis/kafka/v1alpha1.BrokerOperatorSpec", "github.com/example-inc/app-operator/pkg/apis/kafka/v1alpha1.BrokerOperatorStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_pkg_apis_kafka_v1alpha1_BrokerOperatorSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "BrokerOperatorSpec defines the desired state of BrokerOperator",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}

func schema_pkg_apis_kafka_v1alpha1_BrokerOperatorStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "BrokerOperatorStatus defines the observed state of BrokerOperator",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}

func schema_pkg_apis_kafka_v1alpha1_ZooKeeperOperator(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "ZooKeeperOperator is the Schema for the zookeeperoperators API",
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/example-inc/app-operator/pkg/apis/kafka/v1alpha1.ZooKeeperOperatorSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/example-inc/app-operator/pkg/apis/kafka/v1alpha1.ZooKeeperOperatorStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"github.com/example-inc/app-operator/pkg/apis/kafka/v1alpha1.ZooKeeperOperatorSpec", "github.com/example-inc/app-operator/pkg/apis/kafka/v1alpha1.ZooKeeperOperatorStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_pkg_apis_kafka_v1alpha1_ZooKeeperOperatorSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "ZooKeeperOperatorSpec defines the desired state of ZooKeeperOperator",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}

func schema_pkg_apis_kafka_v1alpha1_ZooKeeperOperatorStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "ZooKeeperOperatorStatus defines the observed state of ZooKeeperOperator",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}
